#
# Copyright 2025 Supergate.cc, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""vision.cpp(ggml) 백엔드 코드 생성기 (thin dispatcher).

각 op 의 렌더링은 `nn/modules/<op>.py` 의 ``render(node, ctx)`` 함수에 있고
``@register_render(OP.X)`` 로 등록된다 (shared/compile/render_api.py). 이 generator 는
Graph IR 를 순회하며 `RENDERERS` 로 디스패치하고, 구조적 op(INPUT/FLATTEN/RETURN)만
내장으로 처리한 뒤 visp arch 컨벤션의 `.cpp/.h/.weights.txt` 를 emit 한다.
설계·op매핑: docs/ggml_codegen.md
"""

import os

from shared.compile.render_api import RENDERERS, RenderContext, op_value


class VispCodeGenerator:
    def __init__(self, graph, output_dir, model_name="model", arch=None):
        self.graph = graph
        self.output_dir = output_dir
        self.model_name = model_name
        self.arch = arch or model_name

    # ----------------------------------------------------------------- driver
    def _walk(self, ctx):
        # op 렌더러 등록 트리거 (nn/modules/*.py 의 @register_render)
        import nn.modules  # noqa: F401

        last_var = "x"
        for node in self.graph.nodes:
            ot = op_value(node)

            # --- 구조적 op (전용 모듈 파일 없음) ---
            if ot == "input":
                ctx.bind(node, "x")
                continue
            if ot == "return":
                continue
            if ot == "flatten":
                # flatten(start_dim=1): WHCN 에서 배치(ne[3])는 유지하고 W*H*C 를
                # dim0 으로 모아 [C', N] 를 만든다 → 뒤의 linear(ne[0]=in_features) 와 정합.
                a = ctx.inp(node)
                last_var = ctx.out(
                    node,
                    f"ggml_reshape_2d(m, {a}, "
                    f"{a}->ne[0] * {a}->ne[1] * {a}->ne[2], {a}->ne[3])",
                    hint="flat",
                )
                continue

            render = RENDERERS.get(node.op.type) or RENDERERS.get(ot)
            if render is None:
                a = ctx.inp(node)
                var = ctx.new_var("op")
                ctx.line(
                    f"    tensor {var} = {a}; "
                    f"// TODO(ggml): unhandled op '{node.op.type}' ({node.name})"
                )
                ctx.bind(node, var)
                last_var = var
                continue

            res = render(node, ctx)
            if res is not None:
                last_var = res
        return last_var

    # --------------------------------------------------------------- emitters
    def _emit_source(self, ctx, last_var):
        body = "\n".join(ctx.lines)
        arch_id = self.arch.lower()  # GGUF general.architecture 규약(소문자)
        return f"""// GENERATED BY SuperGate GTX Compiler (ggml/vision.cpp backend), DO NOT EDIT!
#include "visp/arch/{self.model_name}.h"
#include "visp/ml.h"
#include "visp/nn.h"
#include "visp/vision.h"
#include "util/string.h"

#include <string_view>

namespace visp {{

tensor {self.arch}_forward(model_ref m, tensor x, {self.arch}_params const& p) {{
    (void)p;
    // 입력 레이아웃 변환 (TODO: cwhn/whcn 자동 판별)
    x = cwhn_to_contiguous_2d(m, x);

{body}

    x = contiguous_2d_to_cwhn(m, {last_var});
    return compute_graph_output(m, x, "result");
}}

{self.arch}_params {self.arch}_detect_params(model_file const& f) {{
    {self.arch}_params p{{}};
    // GGUF general.architecture 검증 (모델은 정적 unroll 이라 추가 하이퍼파라미터 없음).
    if (std::string_view arch = f.arch(); arch != "{arch_id}") {{
        throw except(
            "Architecture expected to be '{arch_id}', but was '{{}}' ({{}})",
            arch, f.path);
    }}
    return p;
}}

}} // namespace visp
"""

    def _emit_header(self):
        return f"""// GENERATED BY SuperGate GTX Compiler (ggml/vision.cpp backend), DO NOT EDIT!
#pragma once
#include "visp/ml.h"

namespace visp {{

struct {self.arch}_params {{
    // TODO(ggml): 모델 하이퍼파라미터 (block_count 등)
}};

tensor {self.arch}_forward(model_ref m, tensor x, {self.arch}_params const& p);
{self.arch}_params {self.arch}_detect_params(model_file const& f);

}} // namespace visp
"""

    def _emit_weight_manifest(self, ctx):
        lines = [
            '# GGUF weight manifest (key.suffix) — .cpp 의 m["key"] 와 일치해야 함',
            f"# arch={self.arch}",
        ]
        for key, suffixes in ctx._weights:
            for suf in suffixes:
                lines.append(f"{key}.{suf}")
        return "\n".join(lines) + "\n"

    def generate(self):
        os.makedirs(self.output_dir, exist_ok=True)
        ctx = RenderContext()
        last_var = self._walk(ctx)

        src = self._emit_source(ctx, last_var)
        hdr = self._emit_header()
        man = self._emit_weight_manifest(ctx)

        src_path = os.path.join(self.output_dir, f"{self.model_name}.cpp")
        hdr_path = os.path.join(self.output_dir, f"{self.model_name}.h")
        man_path = os.path.join(self.output_dir, f"{self.model_name}.weights.txt")
        with open(src_path, "w") as f:
            f.write(src)
        with open(hdr_path, "w") as f:
            f.write(hdr)
        with open(man_path, "w") as f:
            f.write(man)

        return {
            "source": src_path,
            "header": hdr_path,
            "weights_manifest": man_path,
        }
