# Copyright (C) Supergate - All Rights Reserved
#  Compiler - Weight Exporter
# numpy 가중치를 fp16 hex C 헤더 파일로 내보내는 모듈

"""
PyTorch 모델의 가중치(numpy ndarray)를  하드웨어에서 사용할 수 있는
fp16 형태의 C 헤더 파일로 변환합니다.

생성 파일:
  - weights.h: 모든 가중치를 static const uint16_t 배열로 선언
  - weights.bin: 바이너리 형태의 가중치 (DDR 로드용)
"""

import os
import struct
import numpy as np
from typing import Dict, List, Optional, Tuple


def float32_to_fp16_hex(value: float) -> int:
    """float32 값을 IEEE 754 fp16으로 변환하여 uint16 정수 반환"""
    fp16 = np.float16(value)
    return int(fp16.view(np.uint16))


def ndarray_to_fp16_array(arr: np.ndarray) -> np.ndarray:
    """numpy 배열을 fp16으로 변환하여 uint16 배열로 반환"""
    flat = arr.flatten().astype(np.float16)
    return flat.view(np.uint16)


class WeightExporter:
    """
    모델 가중치를 C 헤더 파일(.h)과 바이너리 파일(.bin)로 내보냄.
    
    사용법:
        exporter = WeightExporter(output_dir="./output")
        exporter.add_weight("conv1_weight", weight_ndarray, shape=[64, 3, 7, 7])
        exporter.add_weight("bn1_mean", bn_mean_ndarray, shape=[64])
        exporter.export_header()    # → weights.h
        exporter.export_binary()    # → weights.bin
    """
    
    def __init__(self, output_dir: str = "./output"):
        self.output_dir = output_dir
        self.weights: Dict[str, Dict] = {}   # name → {data, shape, offset}
        self._total_bytes = 0
        
    def add_weight(self, name: str, data: np.ndarray, shape: Optional[List[int]] = None):
        """가중치 추가"""
        if shape is None:
            shape = list(data.shape)
        
        # fp16으로 변환
        fp16_data = ndarray_to_fp16_array(data)
        size_bytes = len(fp16_data) * 2  # uint16 = 2 bytes
        
        self.weights[name] = {
            'data': fp16_data,
            'shape': shape,
            'offset': self._total_bytes,
            'size': size_bytes,
            'num_elements': len(fp16_data),
        }
        
        self._total_bytes += size_bytes
        # 64바이트 정렬
        padding = (64 - (self._total_bytes % 64)) % 64
        self._total_bytes += padding
    
    def _sanitize_name(self, name: str) -> str:
        """C 변수명으로 사용할 수 있도록 이름 정리"""
        return name.replace('.', '_').replace('/', '_').replace('-', '_').replace(' ', '_')
    
    def export_header(self, filename: str = "weights.h") -> str:
        """
        weights.h 생성 — 모든 가중치를 static const uint16_t 배열로 선언.
        
        큰 모델의 경우 헤더가 매우 커질 수 있으므로,
        DDR_LOAD_MODE를 활성화하면 offset/size 정보만 포함하고
        실제 데이터는 .bin 파일에서 로드하도록 합니다.
        """
        os.makedirs(self.output_dir, exist_ok=True)
        filepath = os.path.join(self.output_dir, filename)
        
        lines = []
        lines.append("// Auto-generated by  Compiler — DO NOT EDIT")
        lines.append(f"// Total weight size: {self._total_bytes} bytes ({self._total_bytes / 1024:.1f} KB)")
        lines.append("")
        lines.append("#ifndef WEIGHTS_H")
        lines.append("#define WEIGHTS_H")
        lines.append("")
        lines.append("#include <stdint.h>")
        lines.append("")
        
        # DDR 로드 모드 (대용량 가중치용)
        lines.append("// DDR_LOAD_MODE가 정의되면 .bin에서 로드")
        lines.append(f"#define TOTAL_WEIGHT_SIZE {self._total_bytes}")
        lines.append("")
        
        # 각 가중치의 오프셋 및 크기 정의
        lines.append("// Weight offsets and sizes (for DDR load mode)")
        for name, info in self.weights.items():
            cname = self._sanitize_name(name)
            shape_str = "x".join(str(s) for s in info['shape'])
            lines.append(f"#define {cname.upper()}_OFFSET {info['offset']}")
            lines.append(f"#define {cname.upper()}_SIZE   {info['size']}")
            lines.append(f"#define {cname.upper()}_ELEMS  {info['num_elements']}")
            lines.append(f"// shape: [{shape_str}]")
            lines.append("")
        
        # 인라인 가중치 데이터 (DDR 로드 모드가 아닌 경우)
        lines.append("#ifndef DDR_LOAD_MODE")
        lines.append("")
        
        for name, info in self.weights.items():
            cname = self._sanitize_name(name)
            fp16_data = info['data']
            shape_str = ", ".join(str(s) for s in info['shape'])
            
            lines.append(f"// {name} — shape: [{shape_str}], size: {info['size']} bytes")
            lines.append(f"static const uint16_t {cname}[{info['num_elements']}] = {{")
            
            # 한 줄에 16개씩
            row_size = 16
            for i in range(0, len(fp16_data), row_size):
                chunk = fp16_data[i:i+row_size]
                hex_vals = ", ".join(f"0x{v:04X}" for v in chunk)
                if i + row_size < len(fp16_data):
                    lines.append(f"    {hex_vals},")
                else:
                    lines.append(f"    {hex_vals}")
            
            lines.append("};")
            lines.append("")
        
        lines.append("#endif // DDR_LOAD_MODE")
        lines.append("")
        lines.append("#endif // WEIGHTS_H")
        lines.append("")
        
        with open(filepath, 'w') as f:
            f.write('\n'.join(lines))
        
        return filepath
    
    def export_binary(self, filename: str = "weights.bin") -> str:
        """
        weights.bin 생성 — 바이너리 형태의 가중치 파일.
        DDR에 직접 로드하여 사용할 수 있습니다.
        """
        os.makedirs(self.output_dir, exist_ok=True)
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, 'wb') as f:
            for name, info in self.weights.items():
                fp16_data = info['data']
                # uint16 배열을 바이트로 변환
                f.write(fp16_data.tobytes())
                # 64바이트 정렬 패딩
                current_pos = f.tell()
                padding = (64 - (current_pos % 64)) % 64
                if padding > 0:
                    f.write(b'\x00' * padding)
        
        return filepath
    
    def export_address_map(self, ddr_base: int = 0xA0000000, filename: str = "weight_map.h") -> str:
        """
        DDR 주소 매핑 헤더 생성 — 각 가중치의 DDR 절대 주소를 정의.
        """
        os.makedirs(self.output_dir, exist_ok=True)
        filepath = os.path.join(self.output_dir, filename)
        
        lines = []
        lines.append("// Auto-generated by  Compiler — DO NOT EDIT")
        lines.append("// Weight DDR address map")
        lines.append("")
        lines.append("#ifndef WEIGHT_MAP_H")
        lines.append("#define WEIGHT_MAP_H")
        lines.append("")
        lines.append("#include <stdint.h>")
        lines.append("")
        lines.append(f"#define DDR_WEIGHT_BASE 0x{ddr_base:08X}ULL")
        lines.append("")
        
        for name, info in self.weights.items():
            cname = self._sanitize_name(name)
            addr = ddr_base + info['offset']
            lines.append(f"#define {cname.upper()}_DDR_ADDR 0x{addr:08X}ULL")
        
        lines.append("")
        lines.append("#endif // WEIGHT_MAP_H")
        lines.append("")
        
        with open(filepath, 'w') as f:
            f.write('\n'.join(lines))
        
        return filepath
    
    def get_weight_info(self, name: str) -> Optional[Dict]:
        """가중치 정보 조회"""
        return self.weights.get(name)
    
    @property
    def total_size(self) -> int:
        """전체 가중치 크기 (바이트)"""
        return self._total_bytes
