# GENETARED BY SuperGate GTX Compiler, DO NOT EDIT!

import torch
from torch import tensor
import nn

class ResNet(nn.GTX_QuantModel):
    def __init__(self):
        super(ResNet, self).__init__()
        self.module_0 = nn.Module('gtx_input') #ResNet::input_0()
        self.module_1 = nn.Module('gtx_conv2d',in_channels=3, out_channels=64, kernel_size=[7, 7], stride=[2, 2], padding=[3, 3], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Conv2d[conv1]/ret.1()
        self.module_2 = nn.Module('gtx_batch_norm',num_features=64, eps=1e-05, momentum=0.1) #ResNet::ResNet/BatchNorm2d[bn1]/ret.3()
        self.module_3 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/ReLU[relu]/3217()
        self.module_4 = nn.Module('gtx_maxpool',kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], ceil_mode=False) #ResNet::ResNet/MaxPool2d[maxpool]/3232()
        self.module_5 = nn.Module('gtx_conv2d',in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer1]/BasicBlock[0]/Conv2d[conv1]/ret.5()
        self.module_6 = nn.Module('gtx_batch_norm',num_features=64, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer1]/BasicBlock[0]/BatchNorm2d[bn1]/ret.7()
        self.module_7 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer1]/BasicBlock[0]/ReLU[relu]/3261()
        self.module_8 = nn.Module('gtx_conv2d',in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer1]/BasicBlock[0]/Conv2d[conv2]/ret.9()
        self.module_9 = nn.Module('gtx_batch_norm',num_features=64, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer1]/BasicBlock[0]/BatchNorm2d[bn2]/ret.11()
        self.module_10 = nn.Module('gtx_elemwise_add') #ResNet::ResNet/Sequential[layer1]/BasicBlock[0]/3290()
        self.module_11 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer1]/BasicBlock[0]/ReLU[relu]/3291()
        self.module_12 = nn.Module('gtx_conv2d',in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer1]/BasicBlock[1]/Conv2d[conv1]/ret.13()
        self.module_13 = nn.Module('gtx_batch_norm',num_features=64, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer1]/BasicBlock[1]/BatchNorm2d[bn1]/ret.15()
        self.module_14 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer1]/BasicBlock[1]/ReLU[relu]/3319()
        self.module_15 = nn.Module('gtx_conv2d',in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer1]/BasicBlock[1]/Conv2d[conv2]/ret.17()
        self.module_16 = nn.Module('gtx_batch_norm',num_features=64, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer1]/BasicBlock[1]/BatchNorm2d[bn2]/ret.19()
        self.module_17 = nn.Module('gtx_elemwise_add') #ResNet::ResNet/Sequential[layer1]/BasicBlock[1]/3348()
        self.module_18 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer1]/BasicBlock[1]/ReLU[relu]/3349()
        self.module_19 = nn.Module('gtx_conv2d',in_channels=64, out_channels=128, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer2]/BasicBlock[0]/Conv2d[conv1]/ret.21()
        self.module_20 = nn.Module('gtx_batch_norm',num_features=128, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer2]/BasicBlock[0]/BatchNorm2d[bn1]/ret.23()
        self.module_21 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer2]/BasicBlock[0]/ReLU[relu]/3377()
        self.module_22 = nn.Module('gtx_conv2d',in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer2]/BasicBlock[0]/Conv2d[conv2]/ret.25()
        self.module_23 = nn.Module('gtx_batch_norm',num_features=128, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer2]/BasicBlock[0]/BatchNorm2d[bn2]/ret.27()
        self.module_24 = nn.Module('gtx_conv2d',in_channels=64, out_channels=128, kernel_size=[1, 1], stride=[2, 2], padding=[0, 0], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer2]/BasicBlock[0]/Sequential[downsample]/Conv2d[0]/ret.29()
        self.module_25 = nn.Module('gtx_batch_norm',num_features=128, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer2]/BasicBlock[0]/Sequential[downsample]/BatchNorm2d[1]/ret.31()
        self.module_26 = nn.Module('gtx_elemwise_add') #ResNet::ResNet/Sequential[layer2]/BasicBlock[0]/3433()
        self.module_27 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer2]/BasicBlock[0]/ReLU[relu]/3434()
        self.module_28 = nn.Module('gtx_conv2d',in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer2]/BasicBlock[1]/Conv2d[conv1]/ret.33()
        self.module_29 = nn.Module('gtx_batch_norm',num_features=128, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer2]/BasicBlock[1]/BatchNorm2d[bn1]/ret.35()
        self.module_30 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer2]/BasicBlock[1]/ReLU[relu]/3462()
        self.module_31 = nn.Module('gtx_conv2d',in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer2]/BasicBlock[1]/Conv2d[conv2]/ret.37()
        self.module_32 = nn.Module('gtx_batch_norm',num_features=128, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer2]/BasicBlock[1]/BatchNorm2d[bn2]/ret.39()
        self.module_33 = nn.Module('gtx_elemwise_add') #ResNet::ResNet/Sequential[layer2]/BasicBlock[1]/3491()
        self.module_34 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer2]/BasicBlock[1]/ReLU[relu]/3492()
        self.module_35 = nn.Module('gtx_conv2d',in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer3]/BasicBlock[0]/Conv2d[conv1]/ret.41()
        self.module_36 = nn.Module('gtx_batch_norm',num_features=256, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer3]/BasicBlock[0]/BatchNorm2d[bn1]/ret.43()
        self.module_37 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer3]/BasicBlock[0]/ReLU[relu]/3520()
        self.module_38 = nn.Module('gtx_conv2d',in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer3]/BasicBlock[0]/Conv2d[conv2]/ret.45()
        self.module_39 = nn.Module('gtx_batch_norm',num_features=256, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer3]/BasicBlock[0]/BatchNorm2d[bn2]/ret.47()
        self.module_40 = nn.Module('gtx_conv2d',in_channels=128, out_channels=256, kernel_size=[1, 1], stride=[2, 2], padding=[0, 0], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer3]/BasicBlock[0]/Sequential[downsample]/Conv2d[0]/ret.49()
        self.module_41 = nn.Module('gtx_batch_norm',num_features=256, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer3]/BasicBlock[0]/Sequential[downsample]/BatchNorm2d[1]/ret.51()
        self.module_42 = nn.Module('gtx_elemwise_add') #ResNet::ResNet/Sequential[layer3]/BasicBlock[0]/3576()
        self.module_43 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer3]/BasicBlock[0]/ReLU[relu]/3577()
        self.module_44 = nn.Module('gtx_conv2d',in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer3]/BasicBlock[1]/Conv2d[conv1]/ret.53()
        self.module_45 = nn.Module('gtx_batch_norm',num_features=256, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer3]/BasicBlock[1]/BatchNorm2d[bn1]/ret.55()
        self.module_46 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer3]/BasicBlock[1]/ReLU[relu]/3605()
        self.module_47 = nn.Module('gtx_conv2d',in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer3]/BasicBlock[1]/Conv2d[conv2]/ret.57()
        self.module_48 = nn.Module('gtx_batch_norm',num_features=256, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer3]/BasicBlock[1]/BatchNorm2d[bn2]/ret.59()
        self.module_49 = nn.Module('gtx_elemwise_add') #ResNet::ResNet/Sequential[layer3]/BasicBlock[1]/3634()
        self.module_50 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer3]/BasicBlock[1]/ReLU[relu]/3635()
        self.module_51 = nn.Module('gtx_conv2d',in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer4]/BasicBlock[0]/Conv2d[conv1]/ret.61()
        self.module_52 = nn.Module('gtx_batch_norm',num_features=512, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer4]/BasicBlock[0]/BatchNorm2d[bn1]/ret.63()
        self.module_53 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer4]/BasicBlock[0]/ReLU[relu]/3663()
        self.module_54 = nn.Module('gtx_conv2d',in_channels=512, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer4]/BasicBlock[0]/Conv2d[conv2]/ret.65()
        self.module_55 = nn.Module('gtx_batch_norm',num_features=512, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer4]/BasicBlock[0]/BatchNorm2d[bn2]/ret.67()
        self.module_56 = nn.Module('gtx_conv2d',in_channels=256, out_channels=512, kernel_size=[1, 1], stride=[2, 2], padding=[0, 0], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer4]/BasicBlock[0]/Sequential[downsample]/Conv2d[0]/ret.69()
        self.module_57 = nn.Module('gtx_batch_norm',num_features=512, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer4]/BasicBlock[0]/Sequential[downsample]/BatchNorm2d[1]/ret.71()
        self.module_58 = nn.Module('gtx_elemwise_add') #ResNet::ResNet/Sequential[layer4]/BasicBlock[0]/3719()
        self.module_59 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer4]/BasicBlock[0]/ReLU[relu]/3720()
        self.module_60 = nn.Module('gtx_conv2d',in_channels=512, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer4]/BasicBlock[1]/Conv2d[conv1]/ret.73()
        self.module_61 = nn.Module('gtx_batch_norm',num_features=512, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer4]/BasicBlock[1]/BatchNorm2d[bn1]/ret.75()
        self.module_62 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer4]/BasicBlock[1]/ReLU[relu]/3748()
        self.module_63 = nn.Module('gtx_conv2d',in_channels=512, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=False) #ResNet::ResNet/Sequential[layer4]/BasicBlock[1]/Conv2d[conv2]/ret.77()
        self.module_64 = nn.Module('gtx_batch_norm',num_features=512, eps=1e-05, momentum=0.1) #ResNet::ResNet/Sequential[layer4]/BasicBlock[1]/BatchNorm2d[bn2]/ret.79()
        self.module_65 = nn.Module('gtx_elemwise_add') #ResNet::ResNet/Sequential[layer4]/BasicBlock[1]/3777()
        self.module_66 = nn.Module('gtx_relu',inplace=True) #ResNet::ResNet/Sequential[layer4]/BasicBlock[1]/ReLU[relu]/3778()
        self.module_67 = nn.Module('gtx_adaptive_avg_pool2d',output_size=[1, 1]) #ResNet::ResNet/AdaptiveAvgPool2d[avgpool]/3795()
        self.module_68 = nn.Module('gtx_flatten') #ResNet::ResNet/ret.81()
        self.module_69 = nn.Module('gtx_dense',in_features=512, out_features=1000, bias=True) #ResNet::ResNet/Linear[fc]/ret()

    @nn.forward_processor
    def forward(self, *args):
        output_module_0 = self.module_0(input=args[0])
        output_module_0 = self.module_1(output_module_0)
        output_module_0 = self.module_2(output_module_0)
        output_module_0 = self.module_3(output_module_0)
        output_module_0 = self.module_4(output_module_0)
        output_module_5 = self.module_5(output_module_0)
        output_module_5 = self.module_6(output_module_5)
        output_module_5 = self.module_7(output_module_5)
        output_module_5 = self.module_8(output_module_5)
        output_module_5 = self.module_9(output_module_5)
        output_module_5 = self.module_10(input=output_module_5, other=output_module_0, alpha=1)
        output_module_5 = self.module_11(output_module_5)
        output_module_12 = self.module_12(output_module_5)
        output_module_12 = self.module_13(output_module_12)
        output_module_12 = self.module_14(output_module_12)
        output_module_12 = self.module_15(output_module_12)
        output_module_12 = self.module_16(output_module_12)
        output_module_12 = self.module_17(input=output_module_12, other=output_module_5, alpha=1)
        output_module_12 = self.module_18(output_module_12)
        output_module_19 = self.module_19(output_module_12)
        output_module_19 = self.module_20(output_module_19)
        output_module_19 = self.module_21(output_module_19)
        output_module_19 = self.module_22(output_module_19)
        output_module_19 = self.module_23(output_module_19)
        output_module_24 = self.module_24(output_module_12)
        output_module_24 = self.module_25(output_module_24)
        output_module_19 = self.module_26(input=output_module_19, other=output_module_24, alpha=1)
        output_module_19 = self.module_27(output_module_19)
        output_module_28 = self.module_28(output_module_19)
        output_module_28 = self.module_29(output_module_28)
        output_module_28 = self.module_30(output_module_28)
        output_module_28 = self.module_31(output_module_28)
        output_module_28 = self.module_32(output_module_28)
        output_module_28 = self.module_33(input=output_module_28, other=output_module_19, alpha=1)
        output_module_28 = self.module_34(output_module_28)
        output_module_35 = self.module_35(output_module_28)
        output_module_35 = self.module_36(output_module_35)
        output_module_35 = self.module_37(output_module_35)
        output_module_35 = self.module_38(output_module_35)
        output_module_35 = self.module_39(output_module_35)
        output_module_40 = self.module_40(output_module_28)
        output_module_40 = self.module_41(output_module_40)
        output_module_35 = self.module_42(input=output_module_35, other=output_module_40, alpha=1)
        output_module_35 = self.module_43(output_module_35)
        output_module_44 = self.module_44(output_module_35)
        output_module_44 = self.module_45(output_module_44)
        output_module_44 = self.module_46(output_module_44)
        output_module_44 = self.module_47(output_module_44)
        output_module_44 = self.module_48(output_module_44)
        output_module_44 = self.module_49(input=output_module_44, other=output_module_35, alpha=1)
        output_module_44 = self.module_50(output_module_44)
        output_module_51 = self.module_51(output_module_44)
        output_module_51 = self.module_52(output_module_51)
        output_module_51 = self.module_53(output_module_51)
        output_module_51 = self.module_54(output_module_51)
        output_module_51 = self.module_55(output_module_51)
        output_module_56 = self.module_56(output_module_44)
        output_module_56 = self.module_57(output_module_56)
        output_module_51 = self.module_58(input=output_module_51, other=output_module_56, alpha=1)
        output_module_51 = self.module_59(output_module_51)
        output_module_60 = self.module_60(output_module_51)
        output_module_60 = self.module_61(output_module_60)
        output_module_60 = self.module_62(output_module_60)
        output_module_60 = self.module_63(output_module_60)
        output_module_60 = self.module_64(output_module_60)
        output_module_60 = self.module_65(input=output_module_60, other=output_module_51, alpha=1)
        output_module_60 = self.module_66(output_module_60)
        output_module_60 = self.module_67(output_module_60)
        output_module_60 = self.module_68(input=output_module_60, start_dim=1, end_dim=-1)
        output_module_60 = self.module_69(output_module_60)
        return output_module_60
