/*  ISS RISCV instruction default cycle info */
#ifndef __INSTINFO_H__
#define __INSTINFO_H__
#define LUI_CYC             1
#define AUIPC_CYC           1
#define JAL_CYC             1
#define JALR_CYC            1
#define BEQ_CYC             1
#define BNE_CYC             1
#define BLT_CYC             1
#define BGE_CYC             1
#define BLTU_CYC            1
#define BGEU_CYC            1
#define LB_CYC              1
#define LH_CYC              1
#define LW_CYC              1
#define LBU_CYC             1
#define LHU_CYC             1
#define SB_CYC              1
#define SH_CYC              1
#define SW_CYC              1
#define ADDI_CYC            1
#define SLTI_CYC            1
#define SLTIU_CYC           1
#define XORI_CYC            1
#define ORI_CYC             1
#define ANDI_CYC            1
#define SLLI_CYC            1
#define SRLI_CYC            1
#define SRAI_CYC            1
#define ADD_CYC             1
#define SUB_CYC             1
#define SLL_CYC             1
#define SLT_CYC             1
#define SLTU_CYC            1
#define XOR_CYC             1
#define SRL_CYC             1
#define SRA_CYC             1
#define OR_CYC              1
#define AND_CYC             1
#define FENCE_CYC           1
#define ECALL_CYC           1
#define EBREAK_CYC          1
#define CSRRW_CYC           1
#define CSRRS_CYC           1
#define CSRRC_CYC           1
#define CSRRWI_CYC          1
#define CSRRSI_CYC          1
#define CSRRCI_CYC          1
#define URET_CYC            1
#define SRET_CYC            1
#define MRET_CYC            1
#define WFI_CYC             1
#define SFENCE_CYC          1
#define LWU_CYC             1
#define LD_CYC              1
#define SD_CYC              1
#define ADDIW_CYC           1
#define SLLIW_CYC           1
#define SRLIW_CYC           1
#define SRAIW_CYC           1
#define ADDW_CYC            1
#define SUBW_CYC            1
#define SLLW_CYC            1
#define SRLW_CYC            1
#define SRAW_CYC            1
#define LR_W_CYC            1
#define SC_W_CYC            1
#define AMOSWAP_W_CYC       1
#define AMOADD_W_CYC        1
#define AMOXOR_W_CYC        1
#define AMOAND_W_CYC        1
#define AMOOR_W_CYC         1
#define AMOMIN_W_CYC        1
#define AMOMAX_W_CYC        1
#define AMOMINU_W_CYC       1
#define AMOMAXU_W_CYC       1
#define LR_D_CYC            1
#define SC_D_CYC            1
#define AMOSWAP_D_CYC       1
#define AMOADD_D_CYC        1
#define AMOXOR_D_CYC        1
#define AMOAND_D_CYC        1
#define AMOOR_D_CYC         1
#define AMOMIN_D_CYC        1
#define AMOMAX_D_CYC        1
#define AMOMINU_D_CYC       1
#define AMOMAXU_D_CYC       1
#define ADDI4SPN_CYC        1
#define FLD_CYC             1
#define LW_CYC              1
#define FLW_CYC             1
#define LD_CYC              1
#define FSD_CYC             1
#define SW_CYC              1
#define FSW_CYC             1
#define SD_CYC              1
#define NOP_CYC             1
#define ADDI_CYC            1
#define JAL_CYC             1
#define ADDIW_CYC           1
#define LI_CYC              1
#define ADDI16SP_CYC        1
#define LUI_CYC             1
#define SRLI_CYC            1
#define SRAI_CYC            1
#define ANDI_CYC            1
#define SUB_CYC             1
#define SUBW_CYC            1
#define XOR_CYC             1
#define ADDW_CYC            1
#define OR_CYC              1
#define AND_CYC             1
#define J_CYC               1
#define BEQZ_CYC            1
#define BNEZ_CYC            1
#define SLLI_CYC            1
#define FLDSP_CYC           1
#define LWSP_CYC            1
#define FLWSP_CYC           1
#define LDSP_CYC            1
#define JR_CYC              1
#define MV_CYC              1
#define EBREAK_CYC          1
#define JALR_CYC            1
#define ADD_CYC             1
#define FSDSP_CYC           1
#define SWSP_CYC            1
#define FSWSP_CYC           1
#define SDSP_CYC            1
#define FMADD_S_CYC         1
#define FMSUB_S_CYC         1
#define FNMSUB_S_CYC        1
#define FNMADD_S_CYC        1
#define FADD_S_CYC          1
#define FSUB_S_CYC          1
#define FMUL_S_CYC          1
#define FDIV_S_CYC          1
#define FSQRT_S_CYC         1
#define FSGNJ_S_CYC         1
#define FSGNJN_S_CYC        1
#define FSGNJX_S_CYC        1
#define FMIN_S_CYC          1
#define FMAX_S_CYC          1
#define FCVT_W_S_CYC        1
#define FCVT_WU_S_CYC       1
#define FMV_X_W_CYC         1
#define FEQ_S_CYC           1
#define FLT_S_CYC           1
#define FLE_S_CYC           1
#define FCLASS_S_CYC        1
#define FCVT_S_W_CYC        1
#define FCVT_S_WU_CYC       1
#define FMV_W_X_CYC         1
#define FMADD_D_CYC         1
#define FMSUB_D_CYC         1
#define FNMSUB_D_CYC        1
#define FNMADD_D_CYC        1
#define FADD_D_CYC          1
#define FSUB_D_CYC          1
#define FMUL_D_CYC          1
#define FDIV_D_CYC          1
#define FSQRT_D_CYC         1
#define FSGNJ_D_CYC         1
#define FSGNJN_D_CYC        1
#define FSGNJX_D_CYC        1
#define FMIN_D_CYC          1
#define FMAX_D_CYC          1
#define FCVT_S_D_CYC        1
#define FCVT_D_S_CYC        1
#define FEQ_D_CYC           1
#define FLT_D_CYC           1
#define FLE_D_CYC           1
#define FCLASS_D_CYC        1
#define FCVT_W_D_CYC        1
#define FCVT_WU_D_CYC       1
#define FCVT_D_W_CYC        1
#define FCVT_D_WU_CYC       1
#define FLW_CYC             1
#define FSW_CYC             1
#define FLD_CYC             1
#define FSD_CYC             1
#define FCVT_L_S_CYC        1
#define FCVT_LU_S_CYC       1
#define FCVT_S_L_CYC        1
#define FCVT_S_LU_CYC       1
#define FCVT_L_D_CYC        1
#define FCVT_LU_D_CYC       1
#define FMV_X_D_CYC         1
#define FCVT_D_L_CYC        1
#define FCVT_D_LU_CYC       1
#define FMV_D_X_CYC         1
#define MUL_CYC             1   
#define MULH_CYC            1
#define MULHSU_CYC          1
#define MULHU_CYC           1
#define DIV_CYC             1
#define DIVU_CYC            1
#define REM_CYC             1
#define REMU_CYC            1
#define MULW_CYC            1
#define DIVW_CYC            1
#define DIVUW_CYC           1
#define REMW_CYC            1
#define REMUW_CYC           1
#define MM_CYC              1   
#define MM_S_CYC            1
#define MM_A_CYC            1
#define MM_AS_CYC           1
#define MM_T_CYC            1
#define MMC_CYC             1
#define MMC_S_CYC           1
#define MMC_L_CYC           1
#define MMC_LS_CYC          1
#define MMC_A_CYC           1
#define MMC_AL_CYC          1
#define MMC_T_CYC           1
#define NMCONV_CYC          1
#define DWCONV_CYC          1
#define DSCONV_CYC          1
#define IM2COL_CYC          1
#define SADD_CYC            1
#define SSUB_CYC            1
#define SMUL_CYC            1
#define SDIV_CYC            1
#define SNORM_CYC           1
#define SMAX_CYC            1
#define SMIN_CYC            1
#define SADD_IMM_CYC        1
#define SSUB_IMM_CYC        1
#define SMUL_IMM_CYC        1
#define SDIV_IMM_CYC        1
#define SNORM_IMM_CYC       1
#define SMAX_IMM_CYC        1
#define SMIN_IMM_CYC        1
#define VADD_CYC            1
#define VSUB_CYC            1
#define VMUL_CYC            1
#define VDIV_CYC            1
#define VDOT_CYC            1
#define VNORM_CYC           1
#define VSUM_CYC            1
#define VSQRT_CYC           1
#define VEXP_CYC            1
#define VADD_IMM_CYC        1
#define VSUB_IMM_CYC        1
#define VMUL_IMM_CYC        1
#define VDIV_IMM_CYC        1
#define VDOT_IMM_CYC        1
#define VNORM_IMM_CYC       1
#define VSUM_IMM_CYC        1
#define VSQRT_IMM_CYC       1
#define VEXP_IMM_CYC        1
#define SCVT_F_I_CYC        1
#define SCVT_I_F_CYC        1
#define SCVT_F_N_CYC        1
#define SCVT_N_F_CYC        1
#define FCVT_S_F_CYC        1
#define FCVT_F_S_CYC        1
#define FCVT_D_F_CYC        1
#define FCVT_F_D_CYC        1
#define RELU_CYC            1
#define RELU6_CYC           1
#define LRELU_CYC           1
#define PRELU_CYC           1
#define GELU_CYC            1
#define TANH_CYC            1
#define SIGM_CYC            1
#define RELU_IMM_CYC        1
#define RELU6_IMM_CYC       1
#define LRELU_IMM_CYC       1
#define PRELU_IMM_CYC       1
#define GELU_IMM_CYC        1
#define TANH_IMM_CYC        1
#define SIGM_IMM_CYC        1
#define ESUM_CYC            1
#define SOFTMAX_CYC         1
#define ESUM_IMM_CYC        1
#define SOFTMAX_IMM_CYC     1
#define POOL_M_CYC          1
#define POOL_A_CYC          1
#define LDSPM_L_CYC         1
#define LDSPM_R_CYC         1
#define LDSPM_3D_CYC        1
#define STSPM_L_CYC         1
#define STSPM_3D_CYC        1
#define LDSPM_G_CYC         1
#define STSPM_G_CYC         1
#define STSPM_S_CYC         1
#define SPM2SPM_CYC         1
#define SPM2MEM_CYC         1
#define MEM2SPM_CYC         1
#define MEM2MEM_CYC         1
#define MCAST_CYC           1
#define RDSPR_S_CYC         1
#define WRSPR_S_CYC         1
#define MVSPR_CYC           1
#define RDSPR_T_CYC         1
#define WRSPR_T_CYC         1
#define CREDIT_LD_INC_CYC   1
#define CREDIT_LD_DEC_CYC   1
#define CREDIT_LD_CHK_CYC   1
#define CREDIT_ST_INC_CYC   1
#define CREDIT_ST_DEC_CYC   1
#define CREDIT_ST_CHK_CYC   1   
#define TRANSP_CYC          1
#define FILL_CYC            1
#define WCREATE_CYC         1
#define WKILL_CYC           1
#define WKILL_A_CYC         1
#define MWARP_CYC           1
#define MQSP_CYC            1
#define UMWARP_CYC          1
#define UMQSP_CYC           1
#define BAR_CYC             1
#define WAIT_CYC            1
#define HALT_CYC            1
#define WSTART_CYC          1
#define WEND_CYC            1
#define WSTART_ID_CYC       1
#define WEND_ID_CYC         1
#define GSTART_ID_CYC       1
#define GEND_ID_CYC         1
#define WSPLIT_CYC          1
#define WJOIN_CYC           1
#endif